title: MNH48 Beringin Font
description: Make Beringin alphabets more accessible

theme: jekyll-theme-midnight
twitter_username: mnh48com
github_username: mnh48
timezone: Asia/Kuala_Lumpur

author:
  name: 'Yaya - NAH @ MNH (hidaya—õ MNH48)'
  url: https://twitter.com/mnh48com

show_downloads: false

plugins:
  - jekyll-redirect-from
  